'use client';

import { useMemo, useState } from 'react';
import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { ArrowRight, BarChart3, BookOpen, Bot, Check, ChevronDown, CircleCheck, ExternalLink, FileCheck2, Fingerprint, Home, Languages, LockKeyhole, MapPin, Menu, MessageCircle, SearchCheck, ShieldCheck, Sparkles, Users, X } from 'lucide-react';

const states = ['Maharashtra', 'Delhi', 'Karnataka', 'West Bengal', 'Tamil Nadu', 'Uttar Pradesh'];
const languages = ['English', 'हिन्दी', 'मराठी', 'বাংলা', 'தமிழ்'];
const trend = [{year:'1951',value:361},{year:'1961',value:439},{year:'1971',value:548},{year:'1981',value:683},{year:'1991',value:846},{year:'2001',value:1029},{year:'2011',value:1211}];
const compare = [{name:'Literacy',rural:68,urban:85},{name:'Workers',rural:42,urban:36},{name:'Women / 100 men',rural:95,urban:93}];
const questions = [
  ['Is this the official Census self-enumeration portal?', 'No. Census Saathi is an educational and preparation prototype. It never submits census responses. When official services become available, use links published by the Office of the Registrar General & Census Commissioner, India.'],
  ['Will I be asked for Aadhaar here?', 'Never. This prototype does not request Aadhaar, document uploads, biometrics, or any real identity number. Mock examples are clearly marked and masked.'],
  ['What is self-enumeration?', 'It is an optional way for households to provide census information themselves during an officially announced window. This simulator only helps you understand the kinds of preparation involved.'],
  ['How do I spot a Census scam?', 'Do not share OTPs, banking passwords, or payments. Verify announcements through censusindia.gov.in and use the safety checklist in this prototype before following a link.'],
];

function Logo(){return <a href="#top" className="flex items-center gap-3 font-semibold tracking-tight"><span className="grid size-10 place-items-center rounded-xl bg-emerald-900 text-sm text-white">27</span><span>Census Saathi</span></a>}

export default function Home() {
  const [entered,setEntered]=useState(false); const [state,setState]=useState('Maharashtra'); const [language,setLanguage]=useState('English');
  const [mobile,setMobile]=useState(false); const [prep,setPrep]=useState(0); const [answer,setAnswer]=useState(0); const [aiOpen,setAiOpen]=useState(false); const [aiText,setAiText]=useState(''); const [aiReply,setAiReply]=useState(''); const [fact,setFact]=useState(''); const [factResult,setFactResult]=useState(''); const [chartMode,setChartMode]=useState<'trend'|'compare'>('trend');
  const greeting=useMemo(()=>language==='हिन्दी'?'नमस्ते':language==='मराठी'?'नमस्कार':'Namaste',[language]);
  const safeInput=(v:string)=>v.replace(/[<>]/g,'').slice(0,180);
  const askAi=()=>{const q=safeInput(aiText.trim()); if(!q)return; setAiText(q); setAiReply(q.toLowerCase().includes('aadhaar')?'Census Saathi will never ask you to enter Aadhaar here. Please rely on official Census India guidance for accepted processes.':'Here’s the simple version: Census 2027 is planned as a digital-first national count. This demo helps you learn and prepare; it does not collect or submit your answers.');};
  const checkFact=()=>{const q=safeInput(fact.trim()); if(!q)return; setFact(q); setFactResult(q.toLowerCase().includes('pay')||q.toLowerCase().includes('otp')?'High-risk claim. Census participation should never require a payment, bank password, or OTP. Do not proceed; verify through the official Census India website.':'Unverified in this offline demo. Cross-check the claim on censusindia.gov.in before sharing or acting on it.');};

  if(!entered) return <main id="top" className="min-h-screen overflow-hidden bg-background text-foreground">
    <nav className="mx-auto flex max-w-7xl items-center justify-between px-5 py-5 md:px-10"><Logo/><div className="flex items-center gap-2 rounded-full border border-emerald-900/10 bg-white/70 px-3 py-2 text-xs font-medium text-emerald-950 shadow-sm"><ShieldCheck className="size-4 text-emerald-700"/>Privacy-first prototype</div></nav>
    <section className="relative mx-auto grid min-h-[calc(100vh-80px)] max-w-7xl items-center gap-14 px-5 pb-16 pt-8 md:grid-cols-[1.08fr_.92fr] md:px-10 md:pt-0">
      <div className="relative z-10 max-w-2xl"><div className="eyebrow"><Sparkles/>Your civic AI companion</div><h1 className="display">Every person.<br/><span>Every story.</span></h1><p className="mt-7 max-w-xl text-balance text-lg leading-8 text-slate-600">Understand Census 2027, prepare with confidence, and explore the story of India—all in your language.</p>
        <div className="mt-9 grid max-w-xl gap-3 sm:grid-cols-2"><Picker icon={<Languages/>} label="Language" value={language} onChange={setLanguage} options={languages}/><Picker icon={<MapPin/>} label="Your state" value={state} onChange={setState} options={states}/></div>
        <button onClick={()=>setEntered(true)} className="primary mt-4">Enter Census Saathi <ArrowRight/></button><p className="mt-4 max-w-lg text-xs leading-5 text-slate-500">No account needed. Choices are kept only for this session. This demo never asks for Aadhaar or real identity documents.</p>
      </div>
      <div className="relative mx-auto w-full max-w-lg" aria-hidden="true"><div className="glow"/><div className="preview-card"><div className="rounded-[1.4rem] bg-emerald-950 p-6 text-white"><div className="flex justify-between text-xs text-emerald-200"><span>YOUR CENSUS JOURNEY</span><span>{state}</span></div><p className="mt-8 text-3xl font-semibold tracking-tight">Ready, one step at a time.</p><div className="mt-8 h-2 overflow-hidden rounded-full bg-white/15"><div className="h-full w-[42%] rounded-full bg-orange-400"/></div><div className="mt-4 flex justify-between text-xs"><span>Learn</span><span>Prepare</span><span className="text-white/45">Official portal</span></div></div><div className="mt-4 grid grid-cols-2 gap-4"><Mini tone="orange" title="NEXT FOR YOU">Try the 3-minute preparation check</Mini><Mini tone="green" title="SAFETY STATUS">No sensitive data requested</Mini></div></div></div>
    </section>
  </main>;

  return <div className="min-h-screen bg-[#f7f7f1] text-slate-900">
    <header className="sticky top-0 z-40 border-b border-emerald-950/10 bg-[#f7f7f1]/90 backdrop-blur-xl"><div className="mx-auto flex h-18 max-w-7xl items-center justify-between px-5 md:px-10"><Logo/><nav className="hidden items-center gap-7 text-sm font-medium text-slate-600 lg:flex"><a href="#journey">My journey</a><a href="#prepare">Prepare</a><a href="#explore">Explore data</a><a href="#safety">Safety</a><a href="#faqs">FAQs</a></nav><div className="flex items-center gap-2"><button onClick={()=>setAiOpen(true)} className="nav-ai"><Sparkles/>Ask Saathi</button><button aria-label="Menu" onClick={()=>setMobile(!mobile)} className="icon-button lg:hidden">{mobile?<X/>:<Menu/>}</button></div></div>{mobile&&<nav className="grid gap-1 border-t bg-white p-4 text-sm font-medium lg:hidden">{['journey','prepare','explore','safety','faqs'].map(x=><a onClick={()=>setMobile(false)} className="rounded-xl px-3 py-3 capitalize hover:bg-emerald-50" key={x} href={'#'+x}>{x}</a>)}</nav>}</header>
    <main>
      <section id="journey" className="mx-auto max-w-7xl px-5 pb-16 pt-10 md:px-10 md:pt-16"><div className="flex flex-col justify-between gap-6 md:flex-row md:items-end"><div><p className="kicker">YOUR PERSONAL GUIDE</p><h1 className="mt-3 text-4xl font-semibold tracking-[-.04em] text-emerald-950 md:text-6xl">{greeting}, {state}.</h1><p className="mt-4 max-w-2xl text-lg text-slate-600">Everything you need to understand and prepare for Census 2027—without sharing personal information.</p></div><button onClick={()=>setEntered(false)} className="secondary"><Languages/>Change language or state</button></div>
        <div className="mt-10 grid gap-5 lg:grid-cols-[1.35fr_.65fr]"><div className="hero-panel"><div className="flex items-center justify-between"><p className="kicker text-emerald-200">YOUR CENSUS TIMELINE</p><span className="status">Information mode</span></div><h2 className="mt-5 max-w-xl text-3xl font-semibold tracking-tight md:text-4xl">Learn now. Prepare calmly. Use only the official portal when announced.</h2><div className="mt-10 grid gap-6 md:grid-cols-3"><Step active n="01" title="Understand" text="How Census 2027 works"/><Step active n="02" title="Prepare" text="Try the safe simulator"/><Step n="03" title="Participate" text="Official dates awaited"/></div></div><div className="rounded-[1.6rem] border border-orange-200 bg-orange-50 p-6"><div className="grid size-11 place-items-center rounded-xl bg-orange-500 text-white"><ShieldCheck/></div><p className="mt-6 text-xs font-semibold uppercase tracking-widest text-orange-800">GOOD TO KNOW</p><h3 className="mt-2 text-xl font-semibold">This is not a submission portal.</h3><p className="mt-3 text-sm leading-6 text-slate-600">We do not collect Aadhaar, documents, addresses, or real census answers.</p><a href="#safety" className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-emerald-900">See how we protect you <ArrowRight className="size-4"/></a></div></div>
      </section>

      <section className="border-y border-emerald-950/10 bg-white py-20"><div className="mx-auto max-w-7xl px-5 md:px-10"><div className="section-heading"><div><p className="kicker">CENSUS 2027, SIMPLIFIED</p><h2>Two phases. One complete picture.</h2></div><p>India’s census counts people and also builds a picture of homes, communities, and how the country is changing.</p></div><div className="mt-10 grid gap-5 md:grid-cols-2"><InfoCard icon={<Home/>} no="PHASE 01" title="Houselisting & Housing Census" text="Information about houses, household facilities, amenities, and assets—collected during an officially announced period." tags={['Housing condition','Water & sanitation','Household amenities']}/><InfoCard icon={<Users/>} no="PHASE 02" title="Population Enumeration" text="Demographic and socioeconomic information about people in each household, gathered in the second phase." tags={['Age & education','Work & migration','Household members']}/></div></div></section>

      <section id="prepare" className="mx-auto max-w-7xl px-5 py-20 md:px-10"><div className="section-heading"><div><p className="kicker">SAFE PRACTICE MODE</p><h2>Prepare, without entering real data.</h2></div><p>A short simulator to understand the process. All examples are fictional and reset when this page closes.</p></div><div className="mt-10 grid overflow-hidden rounded-[2rem] border border-emerald-950/10 bg-white shadow-sm lg:grid-cols-[.7fr_1.3fr]"><div className="bg-emerald-950 p-7 text-white md:p-10"><p className="kicker text-emerald-200">3-MINUTE READINESS CHECK</p><div className="mt-8 space-y-7">{['Household basics','Address format','Review & consent'].map((x,i)=><button key={x} onClick={()=>setPrep(i)} className={'flex w-full items-center gap-4 text-left '+(prep===i?'opacity-100':'opacity-45')}><span className={'grid size-9 place-items-center rounded-full border text-sm '+(prep>i?'border-orange-400 bg-orange-400 text-emerald-950':'border-white/30')}>{prep>i?<Check/>:i+1}</span><span className="font-medium">{x}</span></button>)}</div><div className="mt-12 rounded-2xl bg-white/10 p-4 text-xs leading-5 text-emerald-100"><LockKeyhole className="mb-2 size-5 text-orange-300"/>No answers leave your browser. Do not type real names, addresses, or identity numbers.</div></div><div className="p-7 md:p-10"><p className="text-xs font-semibold uppercase tracking-widest text-orange-700">DEMO STEP {prep+1} OF 3</p>{prep===0&&<DemoStep title="Who lives in this fictional household?" text="Use only the sample options below. No real names are needed."><div className="grid gap-3 sm:grid-cols-3">{['1 person','2–4 people','5+ people'].map((x,i)=><Choice key={x} active={answer===i} onClick={()=>setAnswer(i)}>{x}</Choice>)}</div><DemoNote>Demo household: The sample “Patil family” has 4 fictional members.</DemoNote></DemoStep>}{prep===1&&<DemoStep title="Recognize the address format" text="Real addresses are never requested here."><div className="mock-field"><span>MASKED DEMO ADDRESS</span><strong>Flat ••, Demo Nagar, Pune 411•••</strong></div><DemoNote>Keep house number, street, locality, district, state, and PIN ready only for the authorized official process.</DemoNote></DemoStep>}{prep===2&&<DemoStep title="Review before you consent" text="A trustworthy process tells you what is collected, why, and what happens next."><div className="space-y-3"><CheckRow>Purpose is explained clearly</CheckRow><CheckRow>No banking password or payment requested</CheckRow><CheckRow>You can review before continuing</CheckRow></div><DemoNote>This button completes only the practice. It submits nothing.</DemoNote></DemoStep>}<div className="mt-8 flex gap-3"><button disabled={prep===0} onClick={()=>setPrep(Math.max(0,prep-1))} className="secondary disabled:opacity-40">Back</button><button onClick={()=>setPrep(Math.min(2,prep+1))} className="primary">{prep===2?'Practice complete':'Continue'} <ArrowRight/></button></div></div></div></section>

      <section id="explore" className="bg-emerald-950 py-20 text-white"><div className="mx-auto max-w-7xl px-5 md:px-10"><div className="section-heading dark-heading"><div><p className="kicker text-orange-300">INDIA THROUGH THE NUMBERS</p><h2>See how a country changes.</h2></div><p>Illustrative historical views based on Census of India series. Values are rounded for this educational prototype.</p></div><div className="mt-10 rounded-[2rem] bg-white p-5 text-slate-900 md:p-8"><div className="flex flex-col justify-between gap-5 md:flex-row md:items-center"><div><p className="kicker">HISTORICAL EXPLORER</p><h3 className="mt-2 text-2xl font-semibold">{chartMode==='trend'?'India’s population, 1951–2011':'Rural–urban comparison'}</h3></div><div className="segmented"><button onClick={()=>setChartMode('trend')} className={chartMode==='trend'?'active':''}>Population trend</button><button onClick={()=>setChartMode('compare')} className={chartMode==='compare'?'active':''}>Compare</button></div></div><div className="mt-8 h-80" aria-label="Historical census chart"><ResponsiveContainer width="100%" height="100%">{chartMode==='trend'?<AreaChart data={trend}><defs><linearGradient id="fill" x1="0" x2="0" y1="0" y2="1"><stop offset="0%" stopColor="#ea580c" stopOpacity=".42"/><stop offset="100%" stopColor="#ea580c" stopOpacity=".02"/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="year"/><YAxis unit="m"/><Tooltip/><Area type="monotone" dataKey="value" stroke="#ea580c" strokeWidth={3} fill="url(#fill)"/></AreaChart>:<BarChart data={compare}><CartesianGrid strokeDasharray="3 3" vertical={false}/><XAxis dataKey="name"/><YAxis/><Tooltip/><Bar dataKey="rural" fill="#065f46" radius={[8,8,0,0]}/><Bar dataKey="urban" fill="#f97316" radius={[8,8,0,0]}/></BarChart>}</ResponsiveContainer></div><div className="mt-5 flex flex-col justify-between gap-3 border-t pt-5 md:flex-row md:items-center"><p className="text-xs text-slate-500">Source context: Census of India, 2011 and historical population series • Rounded demo values</p><button onClick={()=>{setAiOpen(true);setAiReply(chartMode==='trend'?'The long curve shows sustained population growth across each census decade. The sharpest absolute gains appear in the later decades, though growth rates and total gains are different measures.':'This comparison shows how national averages can hide differences between rural and urban India. Always check definitions and the census year before comparing.')}} className="secondary"><Sparkles/>Explain this chart with AI</button></div></div></div></section>

      <section id="safety" className="mx-auto max-w-7xl px-5 py-20 md:px-10"><div className="grid gap-12 lg:grid-cols-[.85fr_1.15fr]"><div><p className="kicker">PRIVACY & SAFETY CENTER</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] text-emerald-950 md:text-5xl">Your data should never be the price of understanding.</h2><p className="mt-5 text-lg leading-8 text-slate-600">This prototype is intentionally useful without identity collection. Learn the safety signals before you use any census-related service.</p><div className="mt-8 rounded-2xl border border-orange-200 bg-orange-50 p-5"><div className="flex items-start gap-3"><Fingerprint className="mt-1 text-orange-700"/><div><strong>We never ask for Aadhaar here</strong><p className="mt-1 text-sm leading-6 text-slate-600">No identity numbers, OTPs, banking information, document uploads, or biometrics.</p></div></div></div></div><div className="grid gap-4 sm:grid-cols-2"><Safety icon={<LockKeyhole/>} title="Minimal by design">Only language and state selections are used to personalize this session.</Safety><Safety icon={<FileCheck2/>} title="Mock means mock">Practice fields are labeled and use fictional, masked examples.</Safety><Safety icon={<ExternalLink/>} title="Safer links">Official resources open in a new tab with protective link settings.</Safety><Safety icon={<SearchCheck/>} title="Defensive inputs">Demo questions are length-limited and treated only as plain text.</Safety></div></div>
        <div className="mt-12 rounded-[2rem] border border-emerald-950/10 bg-white p-6 md:p-8"><div className="grid gap-8 lg:grid-cols-[.7fr_1.3fr]"><div><p className="kicker">CLAIM CHECKER</p><h3 className="mt-3 text-2xl font-semibold">Pause before you trust.</h3><p className="mt-3 text-sm leading-6 text-slate-600">Paste a short claim. This offline demo flags obvious scam signals; it is not an authoritative fact-check.</p></div><div><label className="sr-only" htmlFor="fact">Claim to check</label><textarea id="fact" value={fact} onChange={e=>setFact(safeInput(e.target.value))} maxLength={180} placeholder="Example: Pay ₹500 and share your OTP to complete Census 2027" className="input-area"/><div className="mt-3 flex items-center justify-between"><span className="text-xs text-slate-400">{fact.length}/180 • Don’t paste personal data</span><button onClick={checkFact} className="primary">Check claim <SearchCheck/></button></div>{factResult&&<div role="status" className="mt-4 rounded-xl border border-orange-200 bg-orange-50 p-4 text-sm leading-6 text-slate-700"><strong className="text-orange-800">Safety result:</strong> {factResult}</div>}</div></div></div>
      </section>

      <section id="faqs" className="border-y border-emerald-950/10 bg-white py-20"><div className="mx-auto grid max-w-7xl gap-12 px-5 md:px-10 lg:grid-cols-[.65fr_1.35fr]"><div><p className="kicker">CLEAR ANSWERS</p><h2 className="mt-4 text-4xl font-semibold tracking-[-.04em] text-emerald-950">Questions people ask first.</h2><p className="mt-4 text-slate-600">Need something else? Ask Saathi for a simple explanation.</p><button onClick={()=>setAiOpen(true)} className="primary mt-6"><MessageCircle/>Ask a question</button></div><div className="divide-y divide-slate-200">{questions.map((q,i)=><Faq key={q[0]} q={q[0]} open={answer===i+10} onClick={()=>setAnswer(answer===i+10?0:i+10)}>{q[1]}</Faq>)}</div></div></section>

      <section className="mx-auto max-w-7xl px-5 py-20 md:px-10"><div className="rounded-[2rem] bg-orange-500 p-8 text-emerald-950 md:p-12"><div className="grid gap-8 lg:grid-cols-[1fr_auto] lg:items-end"><div><p className="kicker">OFFICIAL RESOURCES</p><h2 className="mt-4 max-w-3xl text-4xl font-semibold tracking-[-.04em] md:text-5xl">When it matters, go to the source.</h2><p className="mt-4 max-w-2xl text-emerald-950/75">Always confirm dates, eligibility, and participation steps through the Office of the Registrar General & Census Commissioner, India.</p></div><a href="https://censusindia.gov.in/" target="_blank" rel="noopener noreferrer" className="inline-flex min-h-14 items-center justify-center gap-2 rounded-2xl bg-emerald-950 px-6 font-semibold text-white">Visit Census India <ExternalLink/></a></div></div></section>
    </main>
    <footer className="border-t border-emerald-950/10"><div className="mx-auto flex max-w-7xl flex-col justify-between gap-5 px-5 py-8 text-sm text-slate-500 md:flex-row md:items-center md:px-10"><Logo/><p>Educational prototype • Not affiliated with or endorsed by the Government of India.</p></div></footer>

    {aiOpen&&<div className="fixed inset-0 z-50 flex items-end justify-end bg-emerald-950/20 p-3 backdrop-blur-[2px] sm:p-6" onMouseDown={e=>{if(e.currentTarget===e.target)setAiOpen(false)}}><section role="dialog" aria-modal="true" aria-label="Ask Census Saathi" className="flex max-h-[82vh] w-full max-w-md flex-col overflow-hidden rounded-[1.6rem] bg-white shadow-2xl"><div className="flex items-center justify-between bg-emerald-950 p-5 text-white"><div className="flex items-center gap-3"><span className="grid size-10 place-items-center rounded-xl bg-orange-500 text-emerald-950"><Bot/></span><div><strong>Ask Saathi</strong><p className="text-xs text-emerald-200">Demo answers • No personal data</p></div></div><button onClick={()=>setAiOpen(false)} className="icon-button border-white/20 text-white"><X/></button></div><div className="min-h-52 flex-1 overflow-y-auto bg-[#f7f7f1] p-5"><div className="max-w-[85%] rounded-2xl rounded-tl-sm bg-white p-4 text-sm leading-6 shadow-sm">Namaste! I can explain Census 2027, preparation, data, or safety. Please don’t share names, addresses, Aadhaar, or other personal details.</div>{aiReply&&<div className="ml-auto mt-4 max-w-[88%] rounded-2xl rounded-tr-sm bg-emerald-900 p-4 text-sm leading-6 text-white">{aiReply}</div>}</div><div className="border-t p-4"><label className="sr-only" htmlFor="ai">Ask a question</label><div className="flex gap-2"><input id="ai" value={aiText} onChange={e=>setAiText(safeInput(e.target.value))} onKeyDown={e=>{if(e.key==='Enter')askAi()}} maxLength={180} placeholder="Ask a general question…" className="min-w-0 flex-1 rounded-xl border border-slate-200 px-4 outline-none focus:border-emerald-600"/><button onClick={askAi} aria-label="Send question" className="grid size-12 place-items-center rounded-xl bg-orange-500 text-emerald-950"><ArrowRight/></button></div><p className="mt-2 text-[11px] text-slate-400">Offline scripted demo. Answers may be incomplete—verify important details officially.</p></div></section></div>}
  </div>;
}

function Picker({icon,label,value,onChange,options}:{icon:React.ReactNode,label:string,value:string,onChange:(s:string)=>void,options:string[]}){return <label className="picker"><span>{icon}{label}</span><select aria-label={label} value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function Mini({tone,title,children}:{tone:string,title:string,children:React.ReactNode}){return <div className={'rounded-2xl p-4 '+(tone==='orange'?'bg-orange-50':'bg-emerald-50')}><p className={'text-xs font-semibold '+(tone==='orange'?'text-orange-800':'text-emerald-800')}>{title}</p><p className="mt-4 font-semibold text-slate-900">{children}</p></div>}
function Step({active,n,title,text}:{active?:boolean,n:string,title:string,text:string}){return <div className={active?'':'opacity-45'}><span className="text-xs font-semibold text-orange-300">{n}</span><div className="mt-3 h-1 rounded-full bg-white/15"><div className={'h-full rounded-full '+(active?'w-full bg-orange-400':'w-0')}/></div><strong className="mt-4 block">{title}</strong><p className="mt-1 text-sm text-emerald-100">{text}</p></div>}
function InfoCard({icon,no,title,text,tags}:{icon:React.ReactNode,no:string,title:string,text:string,tags:string[]}){return <article className="rounded-[1.7rem] border border-emerald-950/10 bg-[#f7f7f1] p-7 md:p-9"><div className="flex items-center justify-between"><span className="grid size-12 place-items-center rounded-2xl bg-emerald-900 text-white">{icon}</span><span className="kicker">{no}</span></div><h3 className="mt-8 text-2xl font-semibold tracking-tight text-emerald-950">{title}</h3><p className="mt-3 leading-7 text-slate-600">{text}</p><div className="mt-6 flex flex-wrap gap-2">{tags.map(x=><span key={x} className="rounded-full border border-emerald-900/10 bg-white px-3 py-1.5 text-xs font-medium text-emerald-900">{x}</span>)}</div></article>}
function DemoStep({title,text,children}:{title:string,text:string,children:React.ReactNode}){return <><h3 className="mt-3 text-3xl font-semibold tracking-tight text-emerald-950">{title}</h3><p className="mt-3 text-slate-600">{text}</p><div className="mt-7">{children}</div></>}
function Choice({active,onClick,children}:{active:boolean,onClick:()=>void,children:React.ReactNode}){return <button onClick={onClick} className={'rounded-xl border p-4 text-left text-sm font-semibold transition '+(active?'border-emerald-700 bg-emerald-50 text-emerald-900':'border-slate-200 hover:border-emerald-400')}>{children}</button>}
function DemoNote({children}:{children:React.ReactNode}){return <p className="mt-5 rounded-xl bg-slate-50 p-4 text-sm leading-6 text-slate-600"><strong>Practice note:</strong> {children}</p>}
function CheckRow({children}:{children:React.ReactNode}){return <div className="flex items-center gap-3 rounded-xl border border-emerald-100 bg-emerald-50 p-3 text-sm font-medium"><CircleCheck className="size-5 text-emerald-700"/>{children}</div>}
function Safety({icon,title,children}:{icon:React.ReactNode,title:string,children:React.ReactNode}){return <div className="rounded-2xl border border-emerald-950/10 bg-white p-5"><span className="text-emerald-700">{icon}</span><strong className="mt-4 block">{title}</strong><p className="mt-2 text-sm leading-6 text-slate-600">{children}</p></div>}
function Faq({q,open,onClick,children}:{q:string,open:boolean,onClick:()=>void,children:React.ReactNode}){return <div><button onClick={onClick} aria-expanded={open} className="flex w-full items-center justify-between gap-6 py-6 text-left font-semibold"><span>{q}</span><ChevronDown className={'shrink-0 transition '+(open?'rotate-180':'')}/></button>{open&&<p className="pb-6 pr-10 text-sm leading-7 text-slate-600">{children}</p>}</div>}
